# Используем образ Node.js
FROM node:16

# Рабочая директория
WORKDIR /app

# Копируем зависимости и устанавливаем их
COPY package*.json ./
RUN npm install

# Копируем исходный код
COPY . .

# Запускаем сервер разработки
CMD ["npm", "start"]